name: CI

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build-and-test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [20, 22]

    env:
      ENABLE_WORD_LIST: ${{ github.workspace }}/enable1.txt

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Download ENABLE word list
        shell: bash
        run: |
          set -euo pipefail
          curl -fsSL -o "$ENABLE_WORD_LIST" https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt || true
          if [ -f "$ENABLE_WORD_LIST" ]; then
            echo "Downloaded ENABLE word list to $ENABLE_WORD_LIST"
          else
            echo "ENABLE word list not downloaded; tests will skip the ENABLE suite."
          fi

      - name: Build native addon and TS
        run: npm run build

      - name: Run tests
        run: npm test


